ignorePatterns: 
  - test/fixtures/*/source
  - test/fixtures/react
  - build

parser: '@typescript-eslint/parser'
plugins: 
  - '@typescript-eslint'
extends: 
  - nth
  - plugin:@typescript-eslint/recommended

rules:
  # Is there a case where no-unused-vars doesn't cover this?
  '@typescript-eslint/no-unused-vars': off

  # I don't use @ts comments frivolously.
  '@typescript-eslint/ban-ts-comment': off

  # I don't mistakenly write empty functions.
  '@typescript-eslint/no-empty-function': off

  jsx-quotes: ['warn', 'prefer-single']

env:
  es6: true
  node: true