ignorePatterns: 
  - test/fixtures/*/source
  - test/fixtures/react
  - build

parser: '@typescript-eslint/parser'
plugins: 
  - '@typescript-eslint'
extends: 
  - nth
  - plugin:@typescript-eslint/recommended

env:
  es6: true
  node: true