env:
  jest/globals: true

plugins:
  - jest

rules:
  jest/valid-title: warn
  jest/expect-expect: warn
  jest/no-conditional-expect: warn
  jest/no-standalone-expect: warn
  '@typescript-eslint/no-var-requires': warn
  '@typescript-eslint/no-magic-numbers': off

extends:
  - plugin:jest/recommended
